### ISSUE TITLE
Implement new Java push-parser for client/testing

### ISSUE THREAD

**Issue by susanw1** [susanw1/zscript#47]
Purposes:
* Receive responses and make sense of them (even if they're wrong)
* Analyze a command to ensure it's syntactically and semantically compliant
* Link a response to its command to make sense of what happened, inc through addressing
* Receive Notifications and match them to  a handler
* Check a command matches a device's capabilities
* Cucumber tests, verifying responses

So, the parser needs to know if it's parsing command-sequences or responses (incl notifications), but the syntax is broadly the same between those inputs. 

CommandSequences and ResponseSequences:
* Address (mode): sequence begins with '@', eg `@123.1..6`, conforming to `/@[0-9a-f\.]+/`. A missing number is read as zero. 
* Debug (mode): sequence begins with '#', all chars until '\n' are ignorable.
* Line-numbered (hex): eg `_12ab`

CommandSequences only:
* Locks (hex-string): `%a36b0` applies locks associated with the bits set in the hex-string.
ResponseSequences only:
* Notification (hex): eg `!3T5Pa` - a normal sequence, but possibly without `S` statuses. Sent async, rather than in response to commands.

Roughly:
* `command-sequence :== ( address-seq | comment-seq | full-seq ) '\n'`
* `address-seq` :== '@' ( hex-value '.' )* hex-value ( comment-seq | full-seq )`
* `comment-seq :== '#' ( any-excl-nl )*`
*  `full-seq :== [ '%'  hex* | '_' hex-value ] or-seq`
* `or-seq :== and-seq [ '|' and-seq ]`
* `and-seq :== params [ '&' params ]`
* `params :== ( (symbol hex-value) | quoted-string | ( '+' (hex hex)* ) ) +`
* `quoted-string :==  '"' any-excl-nl '"' `
* `symbol :== [A-Z]`
* `hex-value` :== hex{0-4}`
* `hex :== [0-9a-f]`

**Comment by More-Wrong** [comment]
Client side has a parser and structure surrounding it now, as of [#124].
